[project]
name = "huawei-solar"
description = "A Python wrapper for the Huawei Inverter modbus TCP API"
license = { file = "LICENSE.md" }
authors = [
    { name = "wlcrs", email = "wlcrs@users.noreply.github.com" },
    { name = "Emil Vanherp", email = "emil@vanherp.me" },
]
readme = "README.md"
requires-python = ">= 3.12"
keywords = [
    "huawei",
    "solar",
    "sun2000",
    "inverter",
    "battery",
    "modbus",
    "modbus-tcp",
    "modbus-rtu",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Home Automation",
    "Typing :: Typed",

]

dynamic = ["version"]

dependencies = ["tmodbus[async-serial]>=0.5"]

[project.urls]
Homepage = "https://github.com/wlcrs/huawei-solar-lib"
Repository = "https://github.com/wlcrs/huawei-solar-lib"
Issues = "https://github.com/wlcrs/huawei-solar-lib/issues"
Changelog = "https://github.com/wlcrs/huawei-solar-lib/releases"


[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
only-packages = true

[tool.hatch.version]
source = "vcs"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["ALL"]

ignore = [
    "COM812", # conflicts with formatter
    "D203",   # 1 blank line required before class docstring
    "D213",   # Multi-line docstring summary should start at the second line

    "S101",   # allow asserts
    "TRY003", # allow exceptions with longer messages.
    "CPY001", # no copyright notices needed
]

pylint.max-args = 6

[tool.ruff.lint.per-file-ignores]
"src/huawei_solar/register_definitions/periods.py" = ["N801"]

[tool.mypy]
# Specify the target platform details in config, so your developers are
# free to run mypy on Windows, Linux, or macOS and get consistent
# results.
platform = "linux"
python_version = "3.12"

# show error messages from unrelated files
follow_imports = "normal"

# suppress errors about unsatisfied imports
ignore_missing_imports = true

# be strict
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
no_implicit_reexport = true
strict_optional = true
warn_incomplete_stub = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true


[tool.pytest.ini_options]
asyncio_mode = "auto"

[dependency-groups]
dev = [
    "codespell>=2.4.3",
    "tox>=4.59",
    "mypy>=2.3.0",
    "pre-commit>=4.6.2",
    "pre-commit-hooks==6.0.0",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.2",
    "yamllint>=1.38.0",
]
