---
name: Testing

on: [push, pull_request, workflow_call] # yamllint disable rule:truthy

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  pytest:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.12", "3.13", "3.14"]
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🏗 Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python }}
      - name: 🏗 Install dependencies
        run: uv sync --all-extras --frozen --dev
      - name: 🚀 Run pytest
        run: uv run pytest tests
